appname: "Sciangai"

layout: "main"

charset: "UTF-8"

template: "xslate"

session: "cookie"
session_cookie_key: "tHIs rANdOm kEy IS NoT vEry rANDom"

engines:
  xslate:
    cache_dir: "/tmp/__sciangai_xslate_cache"
    cache: 1
    path:
      - /
      - ./views

